name: "Container Security with Grype"

on:
  workflow_dispatch:

jobs:
  grype_scan:
    name: Scan Docker Image for Vulnerabilities
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t juice-shop:latest .

      - name: Install Grype with apt
        run: |
          sudo apt-get update
          sudo apt-get install grype
          grype --version  # Verify installation


      - name: Scan Image with Grype
        run: grype juice-shop:latest --output json > grype-results.json

      - name: Upload Grype Results
        uses: actions/upload-artifact@v4
        with:
          name: grype-results
          path: grype-results.json
