name: "DAST OWASP ZAP"

on:
  workflow_dispatch:

permissions:
  issues: write
  contents: write

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Perform DAST

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Start the Application
        run: npm start &
      
      - name: Perform ZAP Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: "http://localhost:3000"
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload ZAP Scan Results
        uses: actions/upload-artifact@v4
        with:
          name: dast-report
          path: owasp-zap-report.html
