name: Deploy Juice Shop

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull Juice Shop Docker Image
        run: docker pull bkimminich/juice-shop

      - name: Deploy Application
        run: docker run -d -p 3000:3000 bkimminich/juice-shop
