name: "Aggregate Security Reports"

on:
  workflow_dispatch:

jobs:
  aggregate:
    runs-on: ubuntu-latest

    steps:
      - name: Download SAST Results
        uses: actions/download-artifact@v4
        with:
          name: sast-results

      - name: Download SCA Results
        uses: actions/download-artifact@v4
        with:
          name: sca-results

      - name: Download DAST Results
        uses: actions/download-artifact@v4
        with:
          name: dast-report

      - name: Download Container Security Results
        uses: actions/download-artifact@v4
        with:
          name: grype-results

      - name: Aggregate Reports
        run: |
          mkdir -p reports
          mv *.json reports/
          zip -r security-reports.zip reports/

      - name: Upload Aggregate Report
        uses: actions/upload-artifact@v4
        with:
          name: aggregate-report
          path: security-reports.zip
