name: Static Application Security Testing (SAST)

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  sast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages:
            - javascript
            - typescript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
