name: "SAST with Semgrep"

on:
  workflow_dispatch:

jobs:
  semgrep:
    name: Static Analysis with Semgrep
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep Scan
        run: semgrep --config p/ci --json > sast-results.json

      - name: Upload SAST Results
        uses: actions/upload-artifact@v4
        with:
          name: sast-results
          path: sast-results.json
